project:
  type: website
  output-dir: docs

website:
  title: "Jessica Diallo"
  navbar:
    left:
      - href: jessdiallo.github.io.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

