project:
  type: website
  output-dir: docs

website:
  title: "Jessica Diallo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: https://jessdiallo.github.io/JDiallo_CV.pdf
        text: CV

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    page-layout: full

